/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import javaassignment.Utility;
import javaassignment.fileHandling;
import javaassignment.*;
import javax.swing.JOptionPane;

/**
 *
 * @author gohyanxi
 */

public class UpdateHostelInformation extends javax.swing.JFrame {

    /**
     * Creates new form UpdateHostelInformation
     */
    private String roomID;
    private String type;
    
    public UpdateHostelInformation() {
        initComponents();
        
    }
    public UpdateHostelInformation(String id,String type) {
       
        initComponents();
         this.roomID = id;
         this.type = type;
         
         if(!id.equalsIgnoreCase("")){
            Utility ult = new Utility();
            ult.setId(id);
            ult.setType(type);
            if(type.equalsIgnoreCase("single")){
                
                jPanel3.removeAll();
                jPanel3.add(singleroomspecification);
                jPanel3.repaint();
                jPanel3.revalidate();
                ult.setFileName(fileHandling.HostelFile);
                ult.displayOnPanel(jPanel1);
            }else if (type.equalsIgnoreCase("doubleroom")){
                jPanel3.removeAll();
                jPanel3.add(doubleroomspecification);
                jPanel3.repaint();
                jPanel3.revalidate();
                ult.setFileName(fileHandling.HostelFile);
                ult.displayOnPanel(jPanel1);
            }else if (type.equalsIgnoreCase("master")){
                jPanel3.removeAll();
                jPanel3.add(masterroomspecification);
                jPanel3.repaint();
                jPanel3.revalidate();
                
                ult.setFileName(fileHandling.HostelFile);
                ult.displayOnPanel(jPanel1);
            }else {
                jPanel3.removeAll();
                jPanel3.add(unitspecification);
                jPanel3.repaint();
                jPanel3.revalidate();
                ult.setFileName(fileHandling.HostelFile);
                ult.displayOnPanel(jPanel1);
            }
           
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtupPrice = new javax.swing.JTextField();
        lblupRoomID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        doubleroomspecification = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblbathroomsize1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblbathroomuser1 = new javax.swing.JLabel();
        singleroomspecification = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblbathroomuser = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblbathroomsize = new javax.swing.JLabel();
        masterroomspecification = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lblbathroomsize2 = new javax.swing.JLabel();
        unitspecification = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblroomnumber = new javax.swing.JLabel();
        lblbathroomnumber = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblupRoomType = new javax.swing.JLabel();
        lblroomsize = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        lblstastus = new javax.swing.JLabel();
        lblstastus1 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        txtgender = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(158, 206, 255));

        btnUpdate.setBackground(new java.awt.Color(23, 118, 221));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(23, 118, 221));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Hostel Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room Type:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RoomID: ");

        txtupPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtupPrice.setText("monthly rent");
        txtupPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtupPriceActionPerformed(evt);
            }
        });

        lblupRoomID.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblupRoomID.setForeground(new java.awt.Color(255, 255, 255));
        lblupRoomID.setText("roomid");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price: RM");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Location:");

        jPanel3.setBackground(new java.awt.Color(203, 228, 255));
        jPanel3.setLayout(new java.awt.CardLayout());

        doubleroomspecification.setBackground(new java.awt.Color(204, 255, 255));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel16.setText("Bathroom size:");

        lblbathroomsize1.setText("bathroom size");

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel15.setText("number of residence");

        lblbathroomuser1.setText("residents number");

        javax.swing.GroupLayout doubleroomspecificationLayout = new javax.swing.GroupLayout(doubleroomspecification);
        doubleroomspecification.setLayout(doubleroomspecificationLayout);
        doubleroomspecificationLayout.setHorizontalGroup(
            doubleroomspecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doubleroomspecificationLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(doubleroomspecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbathroomuser1)
                    .addComponent(jLabel15)
                    .addComponent(lblbathroomsize1)
                    .addComponent(jLabel16))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        doubleroomspecificationLayout.setVerticalGroup(
            doubleroomspecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doubleroomspecificationLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblbathroomsize1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblbathroomuser1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.add(doubleroomspecification, "card3");

        singleroomspecification.setBackground(new java.awt.Color(204, 255, 255));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel12.setText("Bathroom user");

        lblbathroomuser.setText("bathroom users");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel13.setText("Bathroom size:");

        lblbathroomsize.setText("bathroom size");

        javax.swing.GroupLayout singleroomspecificationLayout = new javax.swing.GroupLayout(singleroomspecification);
        singleroomspecification.setLayout(singleroomspecificationLayout);
        singleroomspecificationLayout.setHorizontalGroup(
            singleroomspecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleroomspecificationLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(singleroomspecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbathroomsize)
                    .addComponent(jLabel13)
                    .addComponent(lblbathroomuser)
                    .addComponent(jLabel12))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        singleroomspecificationLayout.setVerticalGroup(
            singleroomspecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleroomspecificationLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblbathroomuser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblbathroomsize)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.add(singleroomspecification, "card2");

        masterroomspecification.setBackground(new java.awt.Color(204, 255, 255));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel17.setText("Bathroom size:");

        lblbathroomsize2.setText("bathroom size");

        javax.swing.GroupLayout masterroomspecificationLayout = new javax.swing.GroupLayout(masterroomspecification);
        masterroomspecification.setLayout(masterroomspecificationLayout);
        masterroomspecificationLayout.setHorizontalGroup(
            masterroomspecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masterroomspecificationLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(lblbathroomsize2)
                .addGap(23, 23, 23))
        );
        masterroomspecificationLayout.setVerticalGroup(
            masterroomspecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterroomspecificationLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(masterroomspecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbathroomsize2)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel3.add(masterroomspecification, "card4");

        unitspecification.setBackground(new java.awt.Color(204, 255, 255));

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel18.setText("Room number:");

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel19.setText("Bathroomnumber:");

        lblroomnumber.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblroomnumber.setText("rooms number");

        lblbathroomnumber.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblbathroomnumber.setText("bathrooms number");

        javax.swing.GroupLayout unitspecificationLayout = new javax.swing.GroupLayout(unitspecification);
        unitspecification.setLayout(unitspecificationLayout);
        unitspecificationLayout.setHorizontalGroup(
            unitspecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unitspecificationLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(unitspecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(unitspecificationLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblroomnumber))
                    .addComponent(lblbathroomnumber)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        unitspecificationLayout.setVerticalGroup(
            unitspecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unitspecificationLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lblroomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblbathroomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.add(unitspecification, "card5");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Room Size:");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender Preference:");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("sqft");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Specification");

        btnCancel.setBackground(new java.awt.Color(23, 118, 221));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Description:");

        lblupRoomType.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblupRoomType.setForeground(new java.awt.Color(255, 255, 255));
        lblupRoomType.setText("type");

        lblroomsize.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblroomsize.setForeground(new java.awt.Color(255, 255, 255));
        lblroomsize.setText("size");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setText("description");
        jScrollPane1.setViewportView(txtDescription);

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel14.setText("Status:");

        lblstastus.setFont(new java.awt.Font("Helvetica Neue", 0, 70)); // NOI18N
        lblstastus.setText("status");

        lblstastus1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblstastus1.setForeground(new java.awt.Color(255, 255, 255));
        lblstastus1.setText("location");

        btndelete.setBackground(new java.awt.Color(255, 51, 102));
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        txtgender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(34, 34, 34))
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblstastus)
                                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblupRoomType)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(lblroomsize)
                                                        .addGap(34, 34, 34)
                                                        .addComponent(jLabel9)))))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(62, 62, 62))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblstastus1)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtupPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(244, 244, 244)
                                    .addComponent(jLabel8)
                                    .addGap(41, 41, 41)
                                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblupRoomID)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblupRoomID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtupPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblupRoomType))
                        .addGap(10, 10, 10)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblroomsize)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblstastus1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblstastus, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 15, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtupPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtupPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtupPriceActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

       dispose();
     // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (lblupRoomType.getText().equalsIgnoreCase("single")){
             Single ho = new Single(lblstastus1.getText(),Double.parseDouble(lblroomsize.getText()) ,txtDescription.getText(),lblstastus.getText(),txtgender.getText(),Double.parseDouble(lblbathroomsize.getText()),Integer.parseInt(lblbathroomuser.getText()));
             ho.setMonthlyRent(txtupPrice.getText());
             ho.setDeposit(Double.parseDouble(txtupPrice.getText()));
             ho.bupdateHostelinformation(fileHandling.HostelFile, roomID);
             
        }
        else if(lblupRoomType.getText().equalsIgnoreCase("doubleroom")){
            DoubleRoom ho1 = new DoubleRoom(lblstastus1.getText(),Double.parseDouble(lblroomsize.getText()) ,txtDescription.getText(),lblstastus.getText(),txtgender.getText(),Double.parseDouble(lblbathroomsize1.getText()),lblbathroomuser1.getText());
            ho1.setMonthlyRent(txtupPrice.getText());
   
            ho1.setNumberOfResidents(lblbathroomuser1.getText());
            ho1.bupdateHostelinformation(fileHandling.HostelFile, roomID);
        }
        else if(lblupRoomType.getText().equalsIgnoreCase("master")){
            Master ho2= new Master(lblstastus1.getText(),Double.parseDouble(lblroomsize.getText()) ,txtDescription.getText(),lblstastus.getText(),txtgender.getText(),Double.parseDouble(lblbathroomsize2.getText()));
            ho2.setMonthlyRent(txtupPrice.getText());
            ho2.bupdateHostelinformation(fileHandling.HostelFile, roomID);
        }
        //applicationid, username,name,email,roomid,type,monthlyrent,deposit,duration,year,month,status
        else {
            Unit ho3= new Unit(lblstastus1.getText(),txtgender.getText(),Double.parseDouble(lblroomsize.getText()) ,lblstastus.getText(),txtDescription.getText(),Integer.parseInt(lblroomnumber.getText()),Integer.parseInt(lblbathroomnumber.getText()));
            ho3.setMonthlyRent(txtupPrice.getText());
            ho3.bupdateHostelinformation(fileHandling.HostelFile, roomID);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        if(lblstastus.getText().equals("available")){
        Utility com = new Utility();
        boolean yes = com.comfirmmessage("are you sure you want to delte  this hostel?");
        if (yes) {
        Payment kk = new Payment();
        kk.deleteoutstandingpayment(fileHandling.HostelFile,lblupRoomID.getText());
        }
        else{
            JOptionPane.showMessageDialog(this, "Operation not done");
        }
        }else{
                JOptionPane.showMessageDialog(this, "Only unrented rooms can be deleted");
        }
        
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateHostelInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateHostelInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateHostelInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateHostelInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btndelete;
    private javax.swing.JPanel doubleroomspecification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbathroomnumber;
    private javax.swing.JLabel lblbathroomsize;
    private javax.swing.JLabel lblbathroomsize1;
    private javax.swing.JLabel lblbathroomsize2;
    private javax.swing.JLabel lblbathroomuser;
    private javax.swing.JLabel lblbathroomuser1;
    private javax.swing.JLabel lblroomnumber;
    private javax.swing.JLabel lblroomsize;
    private javax.swing.JLabel lblstastus;
    private javax.swing.JLabel lblstastus1;
    private javax.swing.JLabel lblupRoomID;
    private javax.swing.JLabel lblupRoomType;
    private javax.swing.JPanel masterroomspecification;
    private javax.swing.JPanel singleroomspecification;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtupPrice;
    private javax.swing.JPanel unitspecification;
    // End of variables declaration//GEN-END:variables
}
